const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Follow,
		C3.Plugins.Touch,
		C3.Behaviors.EightDir,
		C3.Behaviors.shadowcaster,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.progressbar,
		C3.Behaviors.Anchor,
		C3.Behaviors.Timer,
		C3.Plugins.Spritefont2,
		C3.Plugins.Tilemap,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.progressbar.Acts.SetPosToObject,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.progressbar.Acts.SetMaximum,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.ResetEventVar
	];
};
self.C3_JsPropNameTable = [
	{FundoMenu: 0},
	{Logo: 0},
	{Seguir: 0},
	{Sprite: 0},
	{btn_touche: 0},
	{btn_play: 0},
	{cansprint: 0},
	{sprinttime: 0},
	{sprintspeedmult: 0},
	{sprintcooldown: 0},
	{"8Direções": 0},
	{ProjetorDeSombra: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{str_person_paradoo: 0},
	{PlanoDeFundoEmBlocos: 0},
	{state: 0},
	{Sólido: 0},
	{str_lataLixo: 0},
	{Texto: 0},
	{Teclado: 0},
	{str_arvore: 0},
	{str_ruaReta: 0},
	{str_ruaretaInfinita: 0},
	{Âncora: 0},
	{str_barra_progresso: 0},
	{str_grama: 0},
	{str_terra_2: 0},
	{FundoBlocos_Terra2: 0},
	{fundoBloco_gramaBoa: 0},
	{str_gramaBoa: 0},
	{str_casa: 0},
	{str_casa00: 0},
	{str_estradaReta: 0},
	{ste_lixo2: 0},
	{ste_casa01: 0},
	{Arvore1: 0},
	{InicioPraça: 0},
	{Sprite2: 0},
	{Cronômetro: 0},
	{Ste_casa4: 0},
	{Ste_casa3: 0},
	{ste_arvore: 0},
	{ste_arvore3: 0},
	{Sprite6: 0},
	{ste_lixo1: 0},
	{ste_lixo03: 0},
	{ste_banco01: 0},
	{ste_grama: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{CasaFazenda: 0},
	{str_estradaReta2: 0},
	{str_praça: 0},
	{fundoBlocos_grama: 0},
	{TextoTempo: 0},
	{TextoLixo: 0},
	{TextoFinal: 0},
	{Fase1: 0},
	{seta: 0},
	{rio: 0},
	{rio2: 0},
	{str_gramacidade: 0},
	{FonteDeSprites: 0},
	{ste_fazenda: 0},
	{fundoFase2: 0},
	{FundoBlocosFase1: 0},
	{Mosaico: 0},
	{avisoGame1: 0},
	{AvisoFase1: 0},
	{FundoBlocoFase3: 0},
	{Áudio: 0},
	{alert: 0},
	{boasVindas: 0},
	{LixosColetados: 0},
	{ArvorePlantada: 0},
	{TempoRestante: 0},
	{Pontos: 0}
];

self.InstanceType = {
	FundoMenu: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	btn_touche: class extends self.IInstance {},
	btn_play: class extends self.ISpriteInstance {},
	str_person_paradoo: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	str_lataLixo: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Teclado: class extends self.IInstance {},
	str_arvore: class extends self.ISpriteInstance {},
	str_ruaReta: class extends self.ISpriteInstance {},
	str_ruaretaInfinita: class extends self.ITiledBackgroundInstance {},
	str_barra_progresso: class extends self.IProgressBarInstance {},
	str_grama: class extends self.ITiledBackgroundInstance {},
	str_terra_2: class extends self.ISpriteInstance {},
	FundoBlocos_Terra2: class extends self.ITiledBackgroundInstance {},
	fundoBloco_gramaBoa: class extends self.ITiledBackgroundInstance {},
	str_gramaBoa: class extends self.ISpriteInstance {},
	str_casa: class extends self.ISpriteInstance {},
	str_casa00: class extends self.ISpriteInstance {},
	str_estradaReta: class extends self.ISpriteInstance {},
	ste_lixo2: class extends self.ITiledBackgroundInstance {},
	ste_casa01: class extends self.ITiledBackgroundInstance {},
	Arvore1: class extends self.ITiledBackgroundInstance {},
	InicioPraça: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Ste_casa4: class extends self.ISpriteInstance {},
	Ste_casa3: class extends self.ISpriteInstance {},
	ste_arvore: class extends self.ISpriteInstance {},
	ste_arvore3: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	ste_lixo1: class extends self.ISpriteInstance {},
	ste_lixo03: class extends self.ISpriteInstance {},
	ste_banco01: class extends self.ISpriteInstance {},
	ste_grama: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	CasaFazenda: class extends self.ISpriteInstance {},
	str_estradaReta2: class extends self.ISpriteInstance {},
	str_praça: class extends self.ISpriteInstance {},
	fundoBlocos_grama: class extends self.ITiledBackgroundInstance {},
	TextoTempo: class extends self.ITextInstance {},
	TextoLixo: class extends self.ITextInstance {},
	TextoFinal: class extends self.ITextInstance {},
	Fase1: class extends self.ITextInstance {},
	seta: class extends self.ISpriteInstance {},
	rio: class extends self.ISpriteInstance {},
	rio2: class extends self.ISpriteInstance {},
	str_gramacidade: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	ste_fazenda: class extends self.ISpriteInstance {},
	fundoFase2: class extends self.ITiledBackgroundInstance {},
	FundoBlocosFase1: class extends self.ITiledBackgroundInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	avisoGame1: class extends self.ISpriteInstance {},
	AvisoFase1: class extends self.ITextInstance {},
	FundoBlocoFase3: class extends self.ITiledBackgroundInstance {},
	Áudio: class extends self.IInstance {},
	alert: class extends self.ITextInstance {},
	boasVindas: class extends self.ITextInstance {}
}